[[redirects]]
  from = "/api/*"
  to = "https://nodejs214.dszcbaross.edu.hu/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/foods/*"
  to = "https://nodejs214.dszcbaross.edu.hu/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}